// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.2
// source: pkg/proto/auth.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_OAuth2Token_FullMethodName     = "/auth.AuthService/OAuth2Token"
	AuthService_OIDCUserInfo_FullMethodName    = "/auth.AuthService/OIDCUserInfo"
	AuthService_OIDCJwks_FullMethodName        = "/auth.AuthService/OIDCJwks"
	AuthService_OIDCDiscovery_FullMethodName   = "/auth.AuthService/OIDCDiscovery"
	AuthService_CheckToken_FullMethodName      = "/auth.AuthService/CheckToken"
	AuthService_GetUserInfo_FullMethodName     = "/auth.AuthService/GetUserInfo"
	AuthService_Login_FullMethodName           = "/auth.AuthService/Login"
	AuthService_GetFullUserInfo_FullMethodName = "/auth.AuthService/GetFullUserInfo"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	OAuth2Token(ctx context.Context, in *OAuth2TokenRequest, opts ...grpc.CallOption) (*OAuth2TokenResponse, error)
	OIDCUserInfo(ctx context.Context, in *OIDCUserInfoRequest, opts ...grpc.CallOption) (*OIDCUserInfoResponse, error)
	OIDCJwks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OIDCJwksResponse, error)
	OIDCDiscovery(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OIDCDiscoveryResponse, error)
	// CheckToken 验证 auth 服务签发的 native token（存储于共享 Redis 的 UUID token）。
	// 其他服务（console 等）通过此接口完成 token 鉴权，无需直连 Redis。
	CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
	// GetUserInfo 根据 user_id 返回昵称、分组等，供远程模式下的调用方填入 context。
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// Login 验证账号密码/OTP，签发 gowk token 并存入 auth Redis。
	// 调用方凭此 token 再通过 CheckToken 完成后续鉴权，无需直连 Redis。
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// GetFullUserInfo 返回完整用户信息（用于 /user/info 接口）。
	GetFullUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*FullUserInfoResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) OAuth2Token(ctx context.Context, in *OAuth2TokenRequest, opts ...grpc.CallOption) (*OAuth2TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OAuth2TokenResponse)
	err := c.cc.Invoke(ctx, AuthService_OAuth2Token_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) OIDCUserInfo(ctx context.Context, in *OIDCUserInfoRequest, opts ...grpc.CallOption) (*OIDCUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OIDCUserInfoResponse)
	err := c.cc.Invoke(ctx, AuthService_OIDCUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) OIDCJwks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OIDCJwksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OIDCJwksResponse)
	err := c.cc.Invoke(ctx, AuthService_OIDCJwks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) OIDCDiscovery(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*OIDCDiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OIDCDiscoveryResponse)
	err := c.cc.Invoke(ctx, AuthService_OIDCDiscovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_CheckToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, AuthService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetFullUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*FullUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FullUserInfoResponse)
	err := c.cc.Invoke(ctx, AuthService_GetFullUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	OAuth2Token(context.Context, *OAuth2TokenRequest) (*OAuth2TokenResponse, error)
	OIDCUserInfo(context.Context, *OIDCUserInfoRequest) (*OIDCUserInfoResponse, error)
	OIDCJwks(context.Context, *emptypb.Empty) (*OIDCJwksResponse, error)
	OIDCDiscovery(context.Context, *emptypb.Empty) (*OIDCDiscoveryResponse, error)
	// CheckToken 验证 auth 服务签发的 native token（存储于共享 Redis 的 UUID token）。
	// 其他服务（console 等）通过此接口完成 token 鉴权，无需直连 Redis。
	CheckToken(context.Context, *CheckTokenRequest) (*CheckTokenResponse, error)
	// GetUserInfo 根据 user_id 返回昵称、分组等，供远程模式下的调用方填入 context。
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// Login 验证账号密码/OTP，签发 gowk token 并存入 auth Redis。
	// 调用方凭此 token 再通过 CheckToken 完成后续鉴权，无需直连 Redis。
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// GetFullUserInfo 返回完整用户信息（用于 /user/info 接口）。
	GetFullUserInfo(context.Context, *GetUserInfoRequest) (*FullUserInfoResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) OAuth2Token(context.Context, *OAuth2TokenRequest) (*OAuth2TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OAuth2Token not implemented")
}
func (UnimplementedAuthServiceServer) OIDCUserInfo(context.Context, *OIDCUserInfoRequest) (*OIDCUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OIDCUserInfo not implemented")
}
func (UnimplementedAuthServiceServer) OIDCJwks(context.Context, *emptypb.Empty) (*OIDCJwksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OIDCJwks not implemented")
}
func (UnimplementedAuthServiceServer) OIDCDiscovery(context.Context, *emptypb.Empty) (*OIDCDiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OIDCDiscovery not implemented")
}
func (UnimplementedAuthServiceServer) CheckToken(context.Context, *CheckTokenRequest) (*CheckTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckToken not implemented")
}
func (UnimplementedAuthServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedAuthServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthServiceServer) GetFullUserInfo(context.Context, *GetUserInfoRequest) (*FullUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFullUserInfo not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_OAuth2Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OAuth2TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).OAuth2Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_OAuth2Token_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).OAuth2Token(ctx, req.(*OAuth2TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_OIDCUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OIDCUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).OIDCUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_OIDCUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).OIDCUserInfo(ctx, req.(*OIDCUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_OIDCJwks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).OIDCJwks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_OIDCJwks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).OIDCJwks(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_OIDCDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).OIDCDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_OIDCDiscovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).OIDCDiscovery(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckToken(ctx, req.(*CheckTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetFullUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetFullUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetFullUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetFullUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OAuth2Token",
			Handler:    _AuthService_OAuth2Token_Handler,
		},
		{
			MethodName: "OIDCUserInfo",
			Handler:    _AuthService_OIDCUserInfo_Handler,
		},
		{
			MethodName: "OIDCJwks",
			Handler:    _AuthService_OIDCJwks_Handler,
		},
		{
			MethodName: "OIDCDiscovery",
			Handler:    _AuthService_OIDCDiscovery_Handler,
		},
		{
			MethodName: "CheckToken",
			Handler:    _AuthService_CheckToken_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _AuthService_GetUserInfo_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AuthService_Login_Handler,
		},
		{
			MethodName: "GetFullUserInfo",
			Handler:    _AuthService_GetFullUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/auth.proto",
}
