// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OAuth2TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantType     string                 `protobuf:"bytes,1,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,6,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Scope         string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	CodeVerifier  string                 `protobuf:"bytes,8,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"` // PKCE support
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2TokenRequest) Reset() {
	*x = OAuth2TokenRequest{}
	mi := &file_pkg_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2TokenRequest) ProtoMessage() {}

func (x *OAuth2TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2TokenRequest.ProtoReflect.Descriptor instead.
func (*OAuth2TokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *OAuth2TokenRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *OAuth2TokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OAuth2TokenRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *OAuth2TokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuth2TokenRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *OAuth2TokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2TokenRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OAuth2TokenRequest) GetCodeVerifier() string {
	if x != nil {
		return x.CodeVerifier
	}
	return ""
}

type OAuth2TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	IdToken       string                 `protobuf:"bytes,6,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuth2TokenResponse) Reset() {
	*x = OAuth2TokenResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuth2TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuth2TokenResponse) ProtoMessage() {}

func (x *OAuth2TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuth2TokenResponse.ProtoReflect.Descriptor instead.
func (*OAuth2TokenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *OAuth2TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *OAuth2TokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *OAuth2TokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *OAuth2TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *OAuth2TokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OAuth2TokenResponse) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type OIDCUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OIDCUserInfoRequest) Reset() {
	*x = OIDCUserInfoRequest{}
	mi := &file_pkg_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCUserInfoRequest) ProtoMessage() {}

func (x *OIDCUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCUserInfoRequest.ProtoReflect.Descriptor instead.
func (*OIDCUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *OIDCUserInfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type OIDCUserInfoResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Sub                 string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email               string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	EmailVerified       bool                   `protobuf:"varint,4,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	GivenName           string                 `protobuf:"bytes,5,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName          string                 `protobuf:"bytes,6,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	MiddleName          string                 `protobuf:"bytes,7,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Nickname            string                 `protobuf:"bytes,8,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PreferredUsername   string                 `protobuf:"bytes,9,opt,name=preferred_username,json=preferredUsername,proto3" json:"preferred_username,omitempty"`
	Picture             string                 `protobuf:"bytes,10,opt,name=picture,proto3" json:"picture,omitempty"`
	PhoneNumber         string                 `protobuf:"bytes,11,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PhoneNumberVerified bool                   `protobuf:"varint,12,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	Locale              string                 `protobuf:"bytes,13,opt,name=locale,proto3" json:"locale,omitempty"`
	UpdatedAt           int64                  `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OIDCUserInfoResponse) Reset() {
	*x = OIDCUserInfoResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCUserInfoResponse) ProtoMessage() {}

func (x *OIDCUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCUserInfoResponse.ProtoReflect.Descriptor instead.
func (*OIDCUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *OIDCUserInfoResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *OIDCUserInfoResponse) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetPreferredUsername() string {
	if x != nil {
		return x.PreferredUsername
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetPhoneNumberVerified() bool {
	if x != nil {
		return x.PhoneNumberVerified
	}
	return false
}

func (x *OIDCUserInfoResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *OIDCUserInfoResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type OIDCJwksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*OIDCJwk             `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OIDCJwksResponse) Reset() {
	*x = OIDCJwksResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCJwksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCJwksResponse) ProtoMessage() {}

func (x *OIDCJwksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCJwksResponse.ProtoReflect.Descriptor instead.
func (*OIDCJwksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *OIDCJwksResponse) GetKeys() []*OIDCJwk {
	if x != nil {
		return x.Keys
	}
	return nil
}

type OIDCJwk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kty           string                 `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	Use           string                 `protobuf:"bytes,2,opt,name=use,proto3" json:"use,omitempty"`
	Kid           string                 `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	N             string                 `protobuf:"bytes,4,opt,name=n,proto3" json:"n,omitempty"`
	E             string                 `protobuf:"bytes,5,opt,name=e,proto3" json:"e,omitempty"`
	Alg           string                 `protobuf:"bytes,6,opt,name=alg,proto3" json:"alg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OIDCJwk) Reset() {
	*x = OIDCJwk{}
	mi := &file_pkg_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCJwk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCJwk) ProtoMessage() {}

func (x *OIDCJwk) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCJwk.ProtoReflect.Descriptor instead.
func (*OIDCJwk) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *OIDCJwk) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *OIDCJwk) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *OIDCJwk) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *OIDCJwk) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *OIDCJwk) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *OIDCJwk) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

type CheckTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenRequest) Reset() {
	*x = CheckTokenRequest{}
	mi := &file_pkg_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenRequest) ProtoMessage() {}

func (x *CheckTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CheckTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CheckTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckTokenResponse) Reset() {
	*x = CheckTokenResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTokenResponse) ProtoMessage() {}

func (x *CheckTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CheckTokenResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckTokenResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_pkg_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserInfoResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type LoginRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Code    string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// device 由调用方注入，通常为 User-Agent。auth 侧落到 Redis 的 token.Device，
	// CheckToken 将其原样回写，供下游做"同账号在多端登录"展示/审计。
	Device        string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LoginResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type FullUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Group         string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	IsVerified    bool                   `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	LastLoginAt   string                 `protobuf:"bytes,9,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	Created       string                 `protobuf:"bytes,10,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullUserInfoResponse) Reset() {
	*x = FullUserInfoResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullUserInfoResponse) ProtoMessage() {}

func (x *FullUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullUserInfoResponse.ProtoReflect.Descriptor instead.
func (*FullUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *FullUserInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FullUserInfoResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *FullUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FullUserInfoResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FullUserInfoResponse) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FullUserInfoResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *FullUserInfoResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *FullUserInfoResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FullUserInfoResponse) GetLastLoginAt() string {
	if x != nil {
		return x.LastLoginAt
	}
	return ""
}

func (x *FullUserInfoResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

type OIDCDiscoveryResponse struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Issuer                           string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	AuthorizationEndpoint            string                 `protobuf:"bytes,2,opt,name=authorization_endpoint,json=authorizationEndpoint,proto3" json:"authorization_endpoint,omitempty"`
	TokenEndpoint                    string                 `protobuf:"bytes,3,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty"`
	UserinfoEndpoint                 string                 `protobuf:"bytes,4,opt,name=userinfo_endpoint,json=userinfoEndpoint,proto3" json:"userinfo_endpoint,omitempty"`
	JwksUri                          string                 `protobuf:"bytes,5,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty"`
	ScopesSupported                  []string               `protobuf:"bytes,6,rep,name=scopes_supported,json=scopesSupported,proto3" json:"scopes_supported,omitempty"`
	ResponseTypesSupported           []string               `protobuf:"bytes,7,rep,name=response_types_supported,json=responseTypesSupported,proto3" json:"response_types_supported,omitempty"`
	GrantTypesSupported              []string               `protobuf:"bytes,8,rep,name=grant_types_supported,json=grantTypesSupported,proto3" json:"grant_types_supported,omitempty"`
	SubjectTypesSupported            []string               `protobuf:"bytes,9,rep,name=subject_types_supported,json=subjectTypesSupported,proto3" json:"subject_types_supported,omitempty"`
	IdTokenSigningAlgValuesSupported []string               `protobuf:"bytes,10,rep,name=id_token_signing_alg_values_supported,json=idTokenSigningAlgValuesSupported,proto3" json:"id_token_signing_alg_values_supported,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *OIDCDiscoveryResponse) Reset() {
	*x = OIDCDiscoveryResponse{}
	mi := &file_pkg_proto_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCDiscoveryResponse) ProtoMessage() {}

func (x *OIDCDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*OIDCDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_auth_proto_rawDescGZIP(), []int{13}
}

func (x *OIDCDiscoveryResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *OIDCDiscoveryResponse) GetAuthorizationEndpoint() string {
	if x != nil {
		return x.AuthorizationEndpoint
	}
	return ""
}

func (x *OIDCDiscoveryResponse) GetTokenEndpoint() string {
	if x != nil {
		return x.TokenEndpoint
	}
	return ""
}

func (x *OIDCDiscoveryResponse) GetUserinfoEndpoint() string {
	if x != nil {
		return x.UserinfoEndpoint
	}
	return ""
}

func (x *OIDCDiscoveryResponse) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *OIDCDiscoveryResponse) GetScopesSupported() []string {
	if x != nil {
		return x.ScopesSupported
	}
	return nil
}

func (x *OIDCDiscoveryResponse) GetResponseTypesSupported() []string {
	if x != nil {
		return x.ResponseTypesSupported
	}
	return nil
}

func (x *OIDCDiscoveryResponse) GetGrantTypesSupported() []string {
	if x != nil {
		return x.GrantTypesSupported
	}
	return nil
}

func (x *OIDCDiscoveryResponse) GetSubjectTypesSupported() []string {
	if x != nil {
		return x.SubjectTypesSupported
	}
	return nil
}

func (x *OIDCDiscoveryResponse) GetIdTokenSigningAlgValuesSupported() []string {
	if x != nil {
		return x.IdTokenSigningAlgValuesSupported
	}
	return nil
}

var File_pkg_proto_auth_proto protoreflect.FileDescriptor

const file_pkg_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"\x8c\x02\n" +
	"\x12OAuth2TokenRequest\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x01 \x01(\tR\tgrantType\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12#\n" +
	"\rrefresh_token\x18\x06 \x01(\tR\frefreshToken\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12#\n" +
	"\rcode_verifier\x18\b \x01(\tR\fcodeVerifier\"\xcc\x01\n" +
	"\x13OAuth2TokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x19\n" +
	"\bid_token\x18\x06 \x01(\tR\aidToken\"8\n" +
	"\x13OIDCUserInfoRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xcd\x03\n" +
	"\x14OIDCUserInfoResponse\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12%\n" +
	"\x0eemail_verified\x18\x04 \x01(\bR\remailVerified\x12\x1d\n" +
	"\n" +
	"given_name\x18\x05 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x06 \x01(\tR\n" +
	"familyName\x12\x1f\n" +
	"\vmiddle_name\x18\a \x01(\tR\n" +
	"middleName\x12\x1a\n" +
	"\bnickname\x18\b \x01(\tR\bnickname\x12-\n" +
	"\x12preferred_username\x18\t \x01(\tR\x11preferredUsername\x12\x18\n" +
	"\apicture\x18\n" +
	" \x01(\tR\apicture\x12!\n" +
	"\fphone_number\x18\v \x01(\tR\vphoneNumber\x122\n" +
	"\x15phone_number_verified\x18\f \x01(\bR\x13phoneNumberVerified\x12\x16\n" +
	"\x06locale\x18\r \x01(\tR\x06locale\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\x03R\tupdatedAt\"5\n" +
	"\x10OIDCJwksResponse\x12!\n" +
	"\x04keys\x18\x01 \x03(\v2\r.auth.OIDCJwkR\x04keys\"m\n" +
	"\aOIDCJwk\x12\x10\n" +
	"\x03kty\x18\x01 \x01(\tR\x03kty\x12\x10\n" +
	"\x03use\x18\x02 \x01(\tR\x03use\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\x12\f\n" +
	"\x01n\x18\x04 \x01(\tR\x01n\x12\f\n" +
	"\x01e\x18\x05 \x01(\tR\x01e\x12\x10\n" +
	"\x03alg\x18\x06 \x01(\tR\x03alg\")\n" +
	"\x11CheckTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"E\n" +
	"\x12CheckTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"`\n" +
	"\x13GetUserInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\"T\n" +
	"\fLoginRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\"r\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\x95\x02\n" +
	"\x14FullUserInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vis_verified\x18\a \x01(\bR\n" +
	"isVerified\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\"\n" +
	"\rlast_login_at\x18\t \x01(\tR\vlastLoginAt\x12\x18\n" +
	"\acreated\x18\n" +
	" \x01(\tR\acreated\"\xf7\x03\n" +
	"\x15OIDCDiscoveryResponse\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x125\n" +
	"\x16authorization_endpoint\x18\x02 \x01(\tR\x15authorizationEndpoint\x12%\n" +
	"\x0etoken_endpoint\x18\x03 \x01(\tR\rtokenEndpoint\x12+\n" +
	"\x11userinfo_endpoint\x18\x04 \x01(\tR\x10userinfoEndpoint\x12\x19\n" +
	"\bjwks_uri\x18\x05 \x01(\tR\ajwksUri\x12)\n" +
	"\x10scopes_supported\x18\x06 \x03(\tR\x0fscopesSupported\x128\n" +
	"\x18response_types_supported\x18\a \x03(\tR\x16responseTypesSupported\x122\n" +
	"\x15grant_types_supported\x18\b \x03(\tR\x13grantTypesSupported\x126\n" +
	"\x17subject_types_supported\x18\t \x03(\tR\x15subjectTypesSupported\x12O\n" +
	"%id_token_signing_alg_values_supported\x18\n" +
	" \x03(\tR idTokenSigningAlgValuesSupported2\x9a\x04\n" +
	"\vAuthService\x12B\n" +
	"\vOAuth2Token\x12\x18.auth.OAuth2TokenRequest\x1a\x19.auth.OAuth2TokenResponse\x12E\n" +
	"\fOIDCUserInfo\x12\x19.auth.OIDCUserInfoRequest\x1a\x1a.auth.OIDCUserInfoResponse\x12:\n" +
	"\bOIDCJwks\x12\x16.google.protobuf.Empty\x1a\x16.auth.OIDCJwksResponse\x12D\n" +
	"\rOIDCDiscovery\x12\x16.google.protobuf.Empty\x1a\x1b.auth.OIDCDiscoveryResponse\x12?\n" +
	"\n" +
	"CheckToken\x12\x17.auth.CheckTokenRequest\x1a\x18.auth.CheckTokenResponse\x12B\n" +
	"\vGetUserInfo\x12\x18.auth.GetUserInfoRequest\x1a\x19.auth.GetUserInfoResponse\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x12G\n" +
	"\x0fGetFullUserInfo\x12\x18.auth.GetUserInfoRequest\x1a\x1a.auth.FullUserInfoResponseB(Z&github.com/iautre/auth/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_auth_proto_rawDescOnce sync.Once
	file_pkg_proto_auth_proto_rawDescData []byte
)

func file_pkg_proto_auth_proto_rawDescGZIP() []byte {
	file_pkg_proto_auth_proto_rawDescOnce.Do(func() {
		file_pkg_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_auth_proto_rawDesc), len(file_pkg_proto_auth_proto_rawDesc)))
	})
	return file_pkg_proto_auth_proto_rawDescData
}

var file_pkg_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pkg_proto_auth_proto_goTypes = []any{
	(*OAuth2TokenRequest)(nil),    // 0: auth.OAuth2TokenRequest
	(*OAuth2TokenResponse)(nil),   // 1: auth.OAuth2TokenResponse
	(*OIDCUserInfoRequest)(nil),   // 2: auth.OIDCUserInfoRequest
	(*OIDCUserInfoResponse)(nil),  // 3: auth.OIDCUserInfoResponse
	(*OIDCJwksResponse)(nil),      // 4: auth.OIDCJwksResponse
	(*OIDCJwk)(nil),               // 5: auth.OIDCJwk
	(*CheckTokenRequest)(nil),     // 6: auth.CheckTokenRequest
	(*CheckTokenResponse)(nil),    // 7: auth.CheckTokenResponse
	(*GetUserInfoRequest)(nil),    // 8: auth.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),   // 9: auth.GetUserInfoResponse
	(*LoginRequest)(nil),          // 10: auth.LoginRequest
	(*LoginResponse)(nil),         // 11: auth.LoginResponse
	(*FullUserInfoResponse)(nil),  // 12: auth.FullUserInfoResponse
	(*OIDCDiscoveryResponse)(nil), // 13: auth.OIDCDiscoveryResponse
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_pkg_proto_auth_proto_depIdxs = []int32{
	5,  // 0: auth.OIDCJwksResponse.keys:type_name -> auth.OIDCJwk
	0,  // 1: auth.AuthService.OAuth2Token:input_type -> auth.OAuth2TokenRequest
	2,  // 2: auth.AuthService.OIDCUserInfo:input_type -> auth.OIDCUserInfoRequest
	14, // 3: auth.AuthService.OIDCJwks:input_type -> google.protobuf.Empty
	14, // 4: auth.AuthService.OIDCDiscovery:input_type -> google.protobuf.Empty
	6,  // 5: auth.AuthService.CheckToken:input_type -> auth.CheckTokenRequest
	8,  // 6: auth.AuthService.GetUserInfo:input_type -> auth.GetUserInfoRequest
	10, // 7: auth.AuthService.Login:input_type -> auth.LoginRequest
	8,  // 8: auth.AuthService.GetFullUserInfo:input_type -> auth.GetUserInfoRequest
	1,  // 9: auth.AuthService.OAuth2Token:output_type -> auth.OAuth2TokenResponse
	3,  // 10: auth.AuthService.OIDCUserInfo:output_type -> auth.OIDCUserInfoResponse
	4,  // 11: auth.AuthService.OIDCJwks:output_type -> auth.OIDCJwksResponse
	13, // 12: auth.AuthService.OIDCDiscovery:output_type -> auth.OIDCDiscoveryResponse
	7,  // 13: auth.AuthService.CheckToken:output_type -> auth.CheckTokenResponse
	9,  // 14: auth.AuthService.GetUserInfo:output_type -> auth.GetUserInfoResponse
	11, // 15: auth.AuthService.Login:output_type -> auth.LoginResponse
	12, // 16: auth.AuthService.GetFullUserInfo:output_type -> auth.FullUserInfoResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_auth_proto_init() }
func file_pkg_proto_auth_proto_init() {
	if File_pkg_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_auth_proto_rawDesc), len(file_pkg_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_auth_proto_goTypes,
		DependencyIndexes: file_pkg_proto_auth_proto_depIdxs,
		MessageInfos:      file_pkg_proto_auth_proto_msgTypes,
	}.Build()
	File_pkg_proto_auth_proto = out.File
	file_pkg_proto_auth_proto_goTypes = nil
	file_pkg_proto_auth_proto_depIdxs = nil
}
