// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthOauth2AuthorizationCode struct {
	Code                string             `json:"code"`
	ClientID            string             `json:"client_id"`
	UserID              int64              `json:"user_id"`
	RedirectUri         pgtype.Text        `json:"redirect_uri"`
	Scope               pgtype.Text        `json:"scope"`
	State               pgtype.Text        `json:"state"`
	Nonce               pgtype.Text        `json:"nonce"`
	CodeChallenge       pgtype.Text        `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text        `json:"code_challenge_method"`
	Expires             pgtype.Timestamptz `json:"expires"`
	Created             pgtype.Timestamptz `json:"created"`
}

type AuthOauth2Client struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Secret          string             `json:"secret"`
	RedirectUris    string             `json:"redirect_uris"`
	Scopes          string             `json:"scopes"`
	GrantTypes      string             `json:"grant_types"`
	AccessTokenTtl  int64              `json:"access_token_ttl"`
	RefreshTokenTtl int64              `json:"refresh_token_ttl"`
	Enabled         bool               `json:"enabled"`
	Created         pgtype.Timestamptz `json:"created"`
	Updated         pgtype.Timestamptz `json:"updated"`
}

type AuthOauth2RefreshToken struct {
	RefreshToken string             `json:"refresh_token"`
	ClientID     string             `json:"client_id"`
	UserID       int64              `json:"user_id"`
	Scope        pgtype.Text        `json:"scope"`
	Expires      pgtype.Timestamptz `json:"expires"`
	Created      pgtype.Timestamptz `json:"created"`
}

type AuthOauth2Token struct {
	AccessToken string             `json:"access_token"`
	TokenType   string             `json:"token_type"`
	ClientID    string             `json:"client_id"`
	UserID      int64              `json:"user_id"`
	Scope       pgtype.Text        `json:"scope"`
	Expires     pgtype.Timestamptz `json:"expires"`
	Created     pgtype.Timestamptz `json:"created"`
}

type AuthOidcJwk struct {
	ID         string             `json:"id"`
	Kid        string             `json:"kid"`
	Kty        string             `json:"kty"`
	Use        string             `json:"use"`
	Alg        string             `json:"alg"`
	N          string             `json:"n"`
	E          string             `json:"e"`
	PrivateKey string             `json:"private_key"`
	Created    pgtype.Timestamptz `json:"created"`
	Updated    pgtype.Timestamptz `json:"updated"`
}

type AuthUser struct {
	ID          int64              `json:"id"`
	Phone       pgtype.Text        `json:"phone"`
	Email       pgtype.Text        `json:"email"`
	Nickname    pgtype.Text        `json:"nickname"`
	Group       pgtype.Text        `json:"group"`
	Enabled     bool               `json:"enabled"`
	Created     pgtype.Timestamptz `json:"created"`
	Updated     pgtype.Timestamptz `json:"updated"`
	Aid         pgtype.Text        `json:"aid"`
	Secret      pgtype.Text        `json:"secret"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	LoginCount  pgtype.Int4        `json:"login_count"`
	Avatar      pgtype.Text        `json:"avatar"`
	IsVerified  pgtype.Bool        `json:"is_verified"`
}
