// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth2.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredAuthorizationCodes = `-- name: CleanupExpiredAuthorizationCodes :exec
DELETE FROM public.auth_oauth2_authorization_code WHERE expires <= NOW()
`

func (q *Queries) CleanupExpiredAuthorizationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredAuthorizationCodes)
	return err
}

const cleanupExpiredRefreshTokens = `-- name: CleanupExpiredRefreshTokens :exec
DELETE FROM public.auth_oauth2_refresh_token WHERE expires <= NOW()
`

func (q *Queries) CleanupExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredRefreshTokens)
	return err
}

const cleanupExpiredTokens = `-- name: CleanupExpiredTokens :exec
DELETE FROM public.auth_oauth2_token WHERE expires <= NOW()
`

func (q *Queries) CleanupExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredTokens)
	return err
}

const consumeOAuth2AuthorizationCode = `-- name: ConsumeOAuth2AuthorizationCode :one
DELETE FROM public.auth_oauth2_authorization_code
WHERE code = $1 AND client_id = $2 AND expires > NOW()
RETURNING code, client_id, user_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, expires, created
`

type ConsumeOAuth2AuthorizationCodeParams struct {
	Code     string `json:"code"`
	ClientID string `json:"client_id"`
}

func (q *Queries) ConsumeOAuth2AuthorizationCode(ctx context.Context, arg ConsumeOAuth2AuthorizationCodeParams) (AuthOauth2AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, consumeOAuth2AuthorizationCode, arg.Code, arg.ClientID)
	var i AuthOauth2AuthorizationCode
	err := row.Scan(
		&i.Code,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const createOAuth2AuthorizationCode = `-- name: CreateOAuth2AuthorizationCode :one
INSERT INTO public.auth_oauth2_authorization_code (code, client_id, user_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, expires, created)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
RETURNING code, client_id, user_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, expires, created
`

type CreateOAuth2AuthorizationCodeParams struct {
	Code                string             `json:"code"`
	ClientID            string             `json:"client_id"`
	UserID              int64              `json:"user_id"`
	RedirectUri         pgtype.Text        `json:"redirect_uri"`
	Scope               pgtype.Text        `json:"scope"`
	State               pgtype.Text        `json:"state"`
	Nonce               pgtype.Text        `json:"nonce"`
	CodeChallenge       pgtype.Text        `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text        `json:"code_challenge_method"`
	Expires             pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateOAuth2AuthorizationCode(ctx context.Context, arg CreateOAuth2AuthorizationCodeParams) (AuthOauth2AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createOAuth2AuthorizationCode,
		arg.Code,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.Scope,
		arg.State,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Expires,
	)
	var i AuthOauth2AuthorizationCode
	err := row.Scan(
		&i.Code,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const createOAuth2Client = `-- name: CreateOAuth2Client :one
INSERT INTO public.auth_oauth2_client (id, name, secret, redirect_uris, scopes, grant_types, access_token_ttl, refresh_token_ttl, enabled, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, secret, redirect_uris, scopes, grant_types, access_token_ttl, refresh_token_ttl, enabled, created, updated
`

type CreateOAuth2ClientParams struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Secret          string             `json:"secret"`
	RedirectUris    string             `json:"redirect_uris"`
	Scopes          string             `json:"scopes"`
	GrantTypes      string             `json:"grant_types"`
	AccessTokenTtl  int64              `json:"access_token_ttl"`
	RefreshTokenTtl int64              `json:"refresh_token_ttl"`
	Enabled         bool               `json:"enabled"`
	Created         pgtype.Timestamptz `json:"created"`
	Updated         pgtype.Timestamptz `json:"updated"`
}

func (q *Queries) CreateOAuth2Client(ctx context.Context, arg CreateOAuth2ClientParams) (AuthOauth2Client, error) {
	row := q.db.QueryRow(ctx, createOAuth2Client,
		arg.ID,
		arg.Name,
		arg.Secret,
		arg.RedirectUris,
		arg.Scopes,
		arg.GrantTypes,
		arg.AccessTokenTtl,
		arg.RefreshTokenTtl,
		arg.Enabled,
		arg.Created,
		arg.Updated,
	)
	var i AuthOauth2Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.RedirectUris,
		&i.Scopes,
		&i.GrantTypes,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.Enabled,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createOAuth2RefreshToken = `-- name: CreateOAuth2RefreshToken :one
INSERT INTO public.auth_oauth2_refresh_token (refresh_token, client_id, user_id, scope, expires, created)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING refresh_token, client_id, user_id, scope, expires, created
`

type CreateOAuth2RefreshTokenParams struct {
	RefreshToken string             `json:"refresh_token"`
	ClientID     string             `json:"client_id"`
	UserID       int64              `json:"user_id"`
	Scope        pgtype.Text        `json:"scope"`
	Expires      pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateOAuth2RefreshToken(ctx context.Context, arg CreateOAuth2RefreshTokenParams) (AuthOauth2RefreshToken, error) {
	row := q.db.QueryRow(ctx, createOAuth2RefreshToken,
		arg.RefreshToken,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.Expires,
	)
	var i AuthOauth2RefreshToken
	err := row.Scan(
		&i.RefreshToken,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const createOAuth2Token = `-- name: CreateOAuth2Token :one
INSERT INTO public.auth_oauth2_token (access_token, token_type, client_id, user_id, scope, expires, created)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING access_token, token_type, client_id, user_id, scope, expires, created
`

type CreateOAuth2TokenParams struct {
	AccessToken string             `json:"access_token"`
	TokenType   string             `json:"token_type"`
	ClientID    string             `json:"client_id"`
	UserID      int64              `json:"user_id"`
	Scope       pgtype.Text        `json:"scope"`
	Expires     pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateOAuth2Token(ctx context.Context, arg CreateOAuth2TokenParams) (AuthOauth2Token, error) {
	row := q.db.QueryRow(ctx, createOAuth2Token,
		arg.AccessToken,
		arg.TokenType,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.Expires,
	)
	var i AuthOauth2Token
	err := row.Scan(
		&i.AccessToken,
		&i.TokenType,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const createOIDCJwk = `-- name: CreateOIDCJwk :one
INSERT INTO public.auth_oidc_jwk (id, kid, kty, use, alg, n, e, private_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, kid, kty, use, alg, n, e, private_key, created, updated
`

type CreateOIDCJwkParams struct {
	ID         string `json:"id"`
	Kid        string `json:"kid"`
	Kty        string `json:"kty"`
	Use        string `json:"use"`
	Alg        string `json:"alg"`
	N          string `json:"n"`
	E          string `json:"e"`
	PrivateKey string `json:"private_key"`
}

func (q *Queries) CreateOIDCJwk(ctx context.Context, arg CreateOIDCJwkParams) (AuthOidcJwk, error) {
	row := q.db.QueryRow(ctx, createOIDCJwk,
		arg.ID,
		arg.Kid,
		arg.Kty,
		arg.Use,
		arg.Alg,
		arg.N,
		arg.E,
		arg.PrivateKey,
	)
	var i AuthOidcJwk
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Kty,
		&i.Use,
		&i.Alg,
		&i.N,
		&i.E,
		&i.PrivateKey,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const disableOAuth2Client = `-- name: DisableOAuth2Client :exec
UPDATE public.auth_oauth2_client set enabled = false
WHERE id = $1
`

func (q *Queries) DisableOAuth2Client(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, disableOAuth2Client, id)
	return err
}

const getActiveOIDCJwks = `-- name: GetActiveOIDCJwks :many
SELECT id, kid, kty, use, alg, n, e, private_key, created, updated
FROM public.auth_oidc_jwk
ORDER BY created DESC
`

func (q *Queries) GetActiveOIDCJwks(ctx context.Context) ([]AuthOidcJwk, error) {
	rows, err := q.db.Query(ctx, getActiveOIDCJwks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthOidcJwk{}
	for rows.Next() {
		var i AuthOidcJwk
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.Kty,
			&i.Use,
			&i.Alg,
			&i.N,
			&i.E,
			&i.PrivateKey,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestOIDCJwk = `-- name: GetLatestOIDCJwk :one
SELECT id, kid, kty, use, alg, n, e, private_key, created, updated
FROM public.auth_oidc_jwk
ORDER BY created DESC
LIMIT 1
`

func (q *Queries) GetLatestOIDCJwk(ctx context.Context) (AuthOidcJwk, error) {
	row := q.db.QueryRow(ctx, getLatestOIDCJwk)
	var i AuthOidcJwk
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Kty,
		&i.Use,
		&i.Alg,
		&i.N,
		&i.E,
		&i.PrivateKey,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getOAuth2AuthorizationCode = `-- name: GetOAuth2AuthorizationCode :one
SELECT code, client_id, user_id, redirect_uri, scope, state, nonce, code_challenge, code_challenge_method, expires, created
FROM public.auth_oauth2_authorization_code
WHERE code = $1 AND expires > NOW()
`

func (q *Queries) GetOAuth2AuthorizationCode(ctx context.Context, code string) (AuthOauth2AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getOAuth2AuthorizationCode, code)
	var i AuthOauth2AuthorizationCode
	err := row.Scan(
		&i.Code,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const getOAuth2Client = `-- name: GetOAuth2Client :one
SELECT id, name, secret, redirect_uris, scopes, grant_types, access_token_ttl, refresh_token_ttl, enabled, created, updated
FROM public.auth_oauth2_client
WHERE id = $1
`

func (q *Queries) GetOAuth2Client(ctx context.Context, id string) (AuthOauth2Client, error) {
	row := q.db.QueryRow(ctx, getOAuth2Client, id)
	var i AuthOauth2Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.RedirectUris,
		&i.Scopes,
		&i.GrantTypes,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.Enabled,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getOAuth2ClientStats = `-- name: GetOAuth2ClientStats :one
SELECT
    c.id,
    c.name,
    COUNT(DISTINCT ac.code) as auth_codes_count,
    COUNT(DISTINCT t.access_token) as active_tokens_count,
    COUNT(DISTINCT rt.refresh_token) as active_refresh_tokens_count
FROM public.auth_oauth2_client c
LEFT JOIN public.auth_oauth2_authorization_code ac ON c.id = ac.client_id
LEFT JOIN public.auth_oauth2_token t ON c.id = t.client_id AND t.expires > NOW()
LEFT JOIN public.auth_oauth2_refresh_token rt ON c.id = rt.client_id AND rt.expires > NOW()
WHERE c.id = $1
GROUP BY c.id, c.name
`

type GetOAuth2ClientStatsRow struct {
	ID                       string `json:"id"`
	Name                     string `json:"name"`
	AuthCodesCount           int64  `json:"auth_codes_count"`
	ActiveTokensCount        int64  `json:"active_tokens_count"`
	ActiveRefreshTokensCount int64  `json:"active_refresh_tokens_count"`
}

func (q *Queries) GetOAuth2ClientStats(ctx context.Context, id string) (GetOAuth2ClientStatsRow, error) {
	row := q.db.QueryRow(ctx, getOAuth2ClientStats, id)
	var i GetOAuth2ClientStatsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthCodesCount,
		&i.ActiveTokensCount,
		&i.ActiveRefreshTokensCount,
	)
	return i, err
}

const getOAuth2RefreshToken = `-- name: GetOAuth2RefreshToken :one
SELECT refresh_token, client_id, user_id, scope, expires, created
FROM public.auth_oauth2_refresh_token
WHERE refresh_token = $1 AND expires > NOW()
`

func (q *Queries) GetOAuth2RefreshToken(ctx context.Context, refreshToken string) (AuthOauth2RefreshToken, error) {
	row := q.db.QueryRow(ctx, getOAuth2RefreshToken, refreshToken)
	var i AuthOauth2RefreshToken
	err := row.Scan(
		&i.RefreshToken,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const getOAuth2RefreshTokensByUser = `-- name: GetOAuth2RefreshTokensByUser :many
SELECT refresh_token, client_id, user_id, scope, expires, created
FROM public.auth_oauth2_refresh_token
WHERE user_id = $1 AND expires > NOW()
ORDER BY created DESC
`

func (q *Queries) GetOAuth2RefreshTokensByUser(ctx context.Context, userID int64) ([]AuthOauth2RefreshToken, error) {
	rows, err := q.db.Query(ctx, getOAuth2RefreshTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthOauth2RefreshToken{}
	for rows.Next() {
		var i AuthOauth2RefreshToken
		if err := rows.Scan(
			&i.RefreshToken,
			&i.ClientID,
			&i.UserID,
			&i.Scope,
			&i.Expires,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuth2Token = `-- name: GetOAuth2Token :one
SELECT access_token, token_type, client_id, user_id, scope, expires, created
FROM public.auth_oauth2_token
WHERE access_token = $1 AND expires > NOW()
`

func (q *Queries) GetOAuth2Token(ctx context.Context, accessToken string) (AuthOauth2Token, error) {
	row := q.db.QueryRow(ctx, getOAuth2Token, accessToken)
	var i AuthOauth2Token
	err := row.Scan(
		&i.AccessToken,
		&i.TokenType,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const getOAuth2TokensByUser = `-- name: GetOAuth2TokensByUser :many
SELECT access_token, token_type, client_id, user_id, scope, expires, created
FROM public.auth_oauth2_token
WHERE user_id = $1 AND expires > NOW()
ORDER BY created DESC
`

func (q *Queries) GetOAuth2TokensByUser(ctx context.Context, userID int64) ([]AuthOauth2Token, error) {
	rows, err := q.db.Query(ctx, getOAuth2TokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthOauth2Token{}
	for rows.Next() {
		var i AuthOauth2Token
		if err := rows.Scan(
			&i.AccessToken,
			&i.TokenType,
			&i.ClientID,
			&i.UserID,
			&i.Scope,
			&i.Expires,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOIDCJwk = `-- name: GetOIDCJwk :one
SELECT id, kid, kty, use, alg, n, e, private_key, created, updated
FROM public.auth_oidc_jwk
WHERE kid = $1
`

func (q *Queries) GetOIDCJwk(ctx context.Context, kid string) (AuthOidcJwk, error) {
	row := q.db.QueryRow(ctx, getOIDCJwk, kid)
	var i AuthOidcJwk
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.Kty,
		&i.Use,
		&i.Alg,
		&i.N,
		&i.E,
		&i.PrivateKey,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listOAuth2Client = `-- name: ListOAuth2Client :many
SELECT id, name, secret, redirect_uris, scopes, grant_types, access_token_ttl, refresh_token_ttl, enabled, created, updated
FROM public.auth_oauth2_client
`

func (q *Queries) ListOAuth2Client(ctx context.Context) ([]AuthOauth2Client, error) {
	rows, err := q.db.Query(ctx, listOAuth2Client)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthOauth2Client{}
	for rows.Next() {
		var i AuthOauth2Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Secret,
			&i.RedirectUris,
			&i.Scopes,
			&i.GrantTypes,
			&i.AccessTokenTtl,
			&i.RefreshTokenTtl,
			&i.Enabled,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCJwks = `-- name: ListOIDCJwks :many
SELECT id, kid, kty, use, alg, n, e, private_key, created, updated
FROM public.auth_oidc_jwk
ORDER BY created DESC
`

func (q *Queries) ListOIDCJwks(ctx context.Context) ([]AuthOidcJwk, error) {
	rows, err := q.db.Query(ctx, listOIDCJwks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthOidcJwk{}
	for rows.Next() {
		var i AuthOidcJwk
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.Kty,
			&i.Use,
			&i.Alg,
			&i.N,
			&i.E,
			&i.PrivateKey,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOAuth2RefreshToken = `-- name: RevokeOAuth2RefreshToken :exec
DELETE FROM public.auth_oauth2_refresh_token WHERE refresh_token = $1
`

func (q *Queries) RevokeOAuth2RefreshToken(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, revokeOAuth2RefreshToken, refreshToken)
	return err
}

const revokeOAuth2RefreshTokensByUser = `-- name: RevokeOAuth2RefreshTokensByUser :exec
DELETE FROM public.auth_oauth2_refresh_token WHERE user_id = $1
`

func (q *Queries) RevokeOAuth2RefreshTokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeOAuth2RefreshTokensByUser, userID)
	return err
}

const revokeOAuth2Token = `-- name: RevokeOAuth2Token :exec
DELETE FROM public.auth_oauth2_token WHERE access_token = $1
`

func (q *Queries) RevokeOAuth2Token(ctx context.Context, accessToken string) error {
	_, err := q.db.Exec(ctx, revokeOAuth2Token, accessToken)
	return err
}

const revokeOAuth2TokensByUser = `-- name: RevokeOAuth2TokensByUser :exec
DELETE FROM public.auth_oauth2_token WHERE user_id = $1
`

func (q *Queries) RevokeOAuth2TokensByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeOAuth2TokensByUser, userID)
	return err
}

const updateOAuth2Client = `-- name: UpdateOAuth2Client :one
UPDATE public.auth_oauth2_client
SET name              = COALESCE(NULLIF($1::varchar, ''), name),
    secret            = COALESCE(NULLIF($2::varchar, ''), secret),
    redirect_uris     = COALESCE(NULLIF($3::text, ''), redirect_uris),
    scopes            = COALESCE(NULLIF($4::text, ''), scopes),
    grant_types       = COALESCE(NULLIF($5::text, ''), grant_types),
    access_token_ttl  = CASE WHEN $6::bigint > 0 THEN $6::bigint ELSE access_token_ttl END,
    refresh_token_ttl = CASE WHEN $7::bigint > 0 THEN $7::bigint ELSE refresh_token_ttl END,
    enabled           = COALESCE($8::boolean, enabled),
    updated           = NOW()
WHERE id = $9
RETURNING id, name, secret, redirect_uris, scopes, grant_types, access_token_ttl, refresh_token_ttl, enabled, created, updated
`

type UpdateOAuth2ClientParams struct {
	Name            string      `json:"name"`
	Secret          string      `json:"secret"`
	RedirectUris    string      `json:"redirect_uris"`
	Scopes          string      `json:"scopes"`
	GrantTypes      string      `json:"grant_types"`
	AccessTokenTtl  int64       `json:"access_token_ttl"`
	RefreshTokenTtl int64       `json:"refresh_token_ttl"`
	Enabled         pgtype.Bool `json:"enabled"`
	ID              string      `json:"id"`
}

// 传空字符串/0 的列不变，仅覆盖显式指定的字段；enabled 仅在显式提供（非 NULL）时覆盖。
func (q *Queries) UpdateOAuth2Client(ctx context.Context, arg UpdateOAuth2ClientParams) (AuthOauth2Client, error) {
	row := q.db.QueryRow(ctx, updateOAuth2Client,
		arg.Name,
		arg.Secret,
		arg.RedirectUris,
		arg.Scopes,
		arg.GrantTypes,
		arg.AccessTokenTtl,
		arg.RefreshTokenTtl,
		arg.Enabled,
		arg.ID,
	)
	var i AuthOauth2Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.RedirectUris,
		&i.Scopes,
		&i.GrantTypes,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.Enabled,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateOAuth2ClientSecret = `-- name: UpdateOAuth2ClientSecret :one
UPDATE public.auth_oauth2_client
SET secret  = $2,
    updated = NOW()
WHERE id = $1
RETURNING id, name, secret, redirect_uris, scopes, grant_types, access_token_ttl, refresh_token_ttl, enabled, created, updated
`

type UpdateOAuth2ClientSecretParams struct {
	ID     string `json:"id"`
	Secret string `json:"secret"`
}

func (q *Queries) UpdateOAuth2ClientSecret(ctx context.Context, arg UpdateOAuth2ClientSecretParams) (AuthOauth2Client, error) {
	row := q.db.QueryRow(ctx, updateOAuth2ClientSecret, arg.ID, arg.Secret)
	var i AuthOauth2Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secret,
		&i.RedirectUris,
		&i.Scopes,
		&i.GrantTypes,
		&i.AccessTokenTtl,
		&i.RefreshTokenTtl,
		&i.Enabled,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
