// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOtpEnrollment = `-- name: ConsumeOtpEnrollment :execrows
DELETE FROM public.auth_otp_enrollment
WHERE token = $1 AND user_id = $2 AND expires > NOW()
`

type ConsumeOtpEnrollmentParams struct {
	Token  string `json:"token"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) ConsumeOtpEnrollment(ctx context.Context, arg ConsumeOtpEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeOtpEnrollment, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOtpCredentialsByUser = `-- name: CountOtpCredentialsByUser :one
SELECT count(*)
FROM public.auth_otp_credential
WHERE user_id = $1
`

func (q *Queries) CountOtpCredentialsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOtpCredentialsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOtpCredential = `-- name: CreateOtpCredential :one
INSERT INTO public.auth_otp_credential (user_id, name, secret)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, secret, last_used_at, created, updated
`

type CreateOtpCredentialParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Secret string `json:"secret"`
}

func (q *Queries) CreateOtpCredential(ctx context.Context, arg CreateOtpCredentialParams) (AuthOtpCredential, error) {
	row := q.db.QueryRow(ctx, createOtpCredential, arg.UserID, arg.Name, arg.Secret)
	var i AuthOtpCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Secret,
		&i.LastUsedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createOtpEnrollment = `-- name: CreateOtpEnrollment :exec
INSERT INTO public.auth_otp_enrollment (token, user_id, name, secret, expires)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOtpEnrollmentParams struct {
	Token   string             `json:"token"`
	UserID  int64              `json:"user_id"`
	Name    string             `json:"name"`
	Secret  string             `json:"secret"`
	Expires pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreateOtpEnrollment(ctx context.Context, arg CreateOtpEnrollmentParams) error {
	_, err := q.db.Exec(ctx, createOtpEnrollment,
		arg.Token,
		arg.UserID,
		arg.Name,
		arg.Secret,
		arg.Expires,
	)
	return err
}

const deleteAllOtpCredentialsByUser = `-- name: DeleteAllOtpCredentialsByUser :execrows
DELETE FROM public.auth_otp_credential
WHERE user_id = $1
`

func (q *Queries) DeleteAllOtpCredentialsByUser(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllOtpCredentialsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredOtpEnrollments = `-- name: DeleteExpiredOtpEnrollments :execrows
DELETE FROM public.auth_otp_enrollment
WHERE expires <= NOW()
`

func (q *Queries) DeleteExpiredOtpEnrollments(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOtpEnrollments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtpCredentialByUser = `-- name: DeleteOtpCredentialByUser :execrows
DELETE FROM public.auth_otp_credential
WHERE id = $1 AND user_id = $2
`

type DeleteOtpCredentialByUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteOtpCredentialByUser(ctx context.Context, arg DeleteOtpCredentialByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtpCredentialByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOtpEnrollment = `-- name: GetOtpEnrollment :one
SELECT token, user_id, name, secret, expires, created
FROM public.auth_otp_enrollment
WHERE token = $1 AND user_id = $2 AND expires > NOW()
`

type GetOtpEnrollmentParams struct {
	Token  string `json:"token"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) GetOtpEnrollment(ctx context.Context, arg GetOtpEnrollmentParams) (AuthOtpEnrollment, error) {
	row := q.db.QueryRow(ctx, getOtpEnrollment, arg.Token, arg.UserID)
	var i AuthOtpEnrollment
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Name,
		&i.Secret,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const listOtpCredentialsByUser = `-- name: ListOtpCredentialsByUser :many
SELECT id, user_id, name, last_used_at, created, updated
FROM public.auth_otp_credential
WHERE user_id = $1
ORDER BY created
`

type ListOtpCredentialsByUserRow struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	Name       string             `json:"name"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	Created    pgtype.Timestamptz `json:"created"`
	Updated    pgtype.Timestamptz `json:"updated"`
}

func (q *Queries) ListOtpCredentialsByUser(ctx context.Context, userID int64) ([]ListOtpCredentialsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOtpCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtpCredentialsByUserRow{}
	for rows.Next() {
		var i ListOtpCredentialsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LastUsedAt,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtpSecretsByUser = `-- name: ListOtpSecretsByUser :many
SELECT id, secret
FROM public.auth_otp_credential
WHERE user_id = $1
ORDER BY created
`

type ListOtpSecretsByUserRow struct {
	ID     int64  `json:"id"`
	Secret string `json:"secret"`
}

func (q *Queries) ListOtpSecretsByUser(ctx context.Context, userID int64) ([]ListOtpSecretsByUserRow, error) {
	rows, err := q.db.Query(ctx, listOtpSecretsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtpSecretsByUserRow{}
	for rows.Next() {
		var i ListOtpSecretsByUserRow
		if err := rows.Scan(&i.ID, &i.Secret); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOtpCredentialAfterLogin = `-- name: UpdateOtpCredentialAfterLogin :execrows
UPDATE public.auth_otp_credential
SET last_used_at = NOW(), updated = NOW()
WHERE id = $1 AND user_id = $2
`

type UpdateOtpCredentialAfterLoginParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) UpdateOtpCredentialAfterLogin(ctx context.Context, arg UpdateOtpCredentialAfterLoginParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOtpCredentialAfterLogin, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
