// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passkey.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasskeyChallenge = `-- name: ConsumePasskeyChallenge :one
DELETE FROM public.auth_passkey_challenge
WHERE token = $1 AND purpose = $2 AND expires > NOW()
RETURNING token, purpose, user_id, session_data, expires, created
`

type ConsumePasskeyChallengeParams struct {
	Token   string `json:"token"`
	Purpose string `json:"purpose"`
}

func (q *Queries) ConsumePasskeyChallenge(ctx context.Context, arg ConsumePasskeyChallengeParams) (AuthPasskeyChallenge, error) {
	row := q.db.QueryRow(ctx, consumePasskeyChallenge, arg.Token, arg.Purpose)
	var i AuthPasskeyChallenge
	err := row.Scan(
		&i.Token,
		&i.Purpose,
		&i.UserID,
		&i.SessionData,
		&i.Expires,
		&i.Created,
	)
	return i, err
}

const countPasskeyCredentialsByUser = `-- name: CountPasskeyCredentialsByUser :one
SELECT count(*)
FROM public.auth_passkey_credential
WHERE user_id = $1
`

func (q *Queries) CountPasskeyCredentialsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPasskeyCredentialsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPasskeyChallenge = `-- name: CreatePasskeyChallenge :exec
INSERT INTO public.auth_passkey_challenge (token, purpose, user_id, session_data, expires)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePasskeyChallengeParams struct {
	Token       string             `json:"token"`
	Purpose     string             `json:"purpose"`
	UserID      pgtype.Int8        `json:"user_id"`
	SessionData []byte             `json:"session_data"`
	Expires     pgtype.Timestamptz `json:"expires"`
}

func (q *Queries) CreatePasskeyChallenge(ctx context.Context, arg CreatePasskeyChallengeParams) error {
	_, err := q.db.Exec(ctx, createPasskeyChallenge,
		arg.Token,
		arg.Purpose,
		arg.UserID,
		arg.SessionData,
		arg.Expires,
	)
	return err
}

const createPasskeyCredential = `-- name: CreatePasskeyCredential :one
INSERT INTO public.auth_passkey_credential (
    user_id, device_info, credential_id, public_key, attestation_type, transports, aaguid,
    sign_count, clone_warning, user_present, user_verified, backup_eligible,
    backup_state, attachment
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14
)
RETURNING id, user_id, name, device_info, credential_id, public_key, attestation_type, transports, aaguid,
          sign_count, clone_warning, user_present, user_verified, backup_eligible,
          backup_state, attachment, last_used_at, created, updated
`

type CreatePasskeyCredentialParams struct {
	UserID          int64  `json:"user_id"`
	DeviceInfo      []byte `json:"device_info"`
	CredentialID    []byte `json:"credential_id"`
	PublicKey       []byte `json:"public_key"`
	AttestationType string `json:"attestation_type"`
	Transports      string `json:"transports"`
	Aaguid          []byte `json:"aaguid"`
	SignCount       int64  `json:"sign_count"`
	CloneWarning    bool   `json:"clone_warning"`
	UserPresent     bool   `json:"user_present"`
	UserVerified    bool   `json:"user_verified"`
	BackupEligible  bool   `json:"backup_eligible"`
	BackupState     bool   `json:"backup_state"`
	Attachment      string `json:"attachment"`
}

func (q *Queries) CreatePasskeyCredential(ctx context.Context, arg CreatePasskeyCredentialParams) (AuthPasskeyCredential, error) {
	row := q.db.QueryRow(ctx, createPasskeyCredential,
		arg.UserID,
		arg.DeviceInfo,
		arg.CredentialID,
		arg.PublicKey,
		arg.AttestationType,
		arg.Transports,
		arg.Aaguid,
		arg.SignCount,
		arg.CloneWarning,
		arg.UserPresent,
		arg.UserVerified,
		arg.BackupEligible,
		arg.BackupState,
		arg.Attachment,
	)
	var i AuthPasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceInfo,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.CloneWarning,
		&i.UserPresent,
		&i.UserVerified,
		&i.BackupEligible,
		&i.BackupState,
		&i.Attachment,
		&i.LastUsedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteExpiredPasskeyChallenges = `-- name: DeleteExpiredPasskeyChallenges :execrows
DELETE FROM public.auth_passkey_challenge
WHERE expires <= NOW()
`

func (q *Queries) DeleteExpiredPasskeyChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasskeyChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePasskeyCredentialByUser = `-- name: DeletePasskeyCredentialByUser :execrows
DELETE FROM public.auth_passkey_credential
WHERE id = $1 AND user_id = $2
`

type DeletePasskeyCredentialByUserParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePasskeyCredentialByUser(ctx context.Context, arg DeletePasskeyCredentialByUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskeyCredentialByUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasskeyCredentialByID = `-- name: GetPasskeyCredentialByID :one
SELECT id, user_id, name, device_info, credential_id, public_key, attestation_type, transports, aaguid,
       sign_count, clone_warning, user_present, user_verified, backup_eligible,
       backup_state, attachment, last_used_at, created, updated
FROM public.auth_passkey_credential
WHERE credential_id = $1
`

func (q *Queries) GetPasskeyCredentialByID(ctx context.Context, credentialID []byte) (AuthPasskeyCredential, error) {
	row := q.db.QueryRow(ctx, getPasskeyCredentialByID, credentialID)
	var i AuthPasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceInfo,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.CloneWarning,
		&i.UserPresent,
		&i.UserVerified,
		&i.BackupEligible,
		&i.BackupState,
		&i.Attachment,
		&i.LastUsedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listPasskeyCredentialsByUser = `-- name: ListPasskeyCredentialsByUser :many
SELECT id, user_id, name, device_info, credential_id, public_key, attestation_type, transports, aaguid,
       sign_count, clone_warning, user_present, user_verified, backup_eligible,
       backup_state, attachment, last_used_at, created, updated
FROM public.auth_passkey_credential
WHERE user_id = $1
ORDER BY created
`

func (q *Queries) ListPasskeyCredentialsByUser(ctx context.Context, userID int64) ([]AuthPasskeyCredential, error) {
	rows, err := q.db.Query(ctx, listPasskeyCredentialsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPasskeyCredential{}
	for rows.Next() {
		var i AuthPasskeyCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DeviceInfo,
			&i.CredentialID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Transports,
			&i.Aaguid,
			&i.SignCount,
			&i.CloneWarning,
			&i.UserPresent,
			&i.UserVerified,
			&i.BackupEligible,
			&i.BackupState,
			&i.Attachment,
			&i.LastUsedAt,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasskeyCredentialAfterAssertion = `-- name: UpdatePasskeyCredentialAfterAssertion :execrows
UPDATE public.auth_passkey_credential
SET sign_count      = $3,
    clone_warning   = $4,
    user_present    = $5,
    user_verified   = $6,
    backup_eligible = $7,
    backup_state    = $8,
    last_used_at    = NOW(),
    updated         = NOW()
WHERE user_id = $1 AND credential_id = $2
`

type UpdatePasskeyCredentialAfterAssertionParams struct {
	UserID         int64  `json:"user_id"`
	CredentialID   []byte `json:"credential_id"`
	SignCount      int64  `json:"sign_count"`
	CloneWarning   bool   `json:"clone_warning"`
	UserPresent    bool   `json:"user_present"`
	UserVerified   bool   `json:"user_verified"`
	BackupEligible bool   `json:"backup_eligible"`
	BackupState    bool   `json:"backup_state"`
}

func (q *Queries) UpdatePasskeyCredentialAfterAssertion(ctx context.Context, arg UpdatePasskeyCredentialAfterAssertionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasskeyCredentialAfterAssertion,
		arg.UserID,
		arg.CredentialID,
		arg.SignCount,
		arg.CloneWarning,
		arg.UserPresent,
		arg.UserVerified,
		arg.BackupEligible,
		arg.BackupState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasskeyCredentialName = `-- name: UpdatePasskeyCredentialName :one
UPDATE public.auth_passkey_credential
SET name = $3, updated = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, device_info, credential_id, public_key, attestation_type, transports, aaguid,
          sign_count, clone_warning, user_present, user_verified, backup_eligible,
          backup_state, attachment, last_used_at, created, updated
`

type UpdatePasskeyCredentialNameParams struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) UpdatePasskeyCredentialName(ctx context.Context, arg UpdatePasskeyCredentialNameParams) (AuthPasskeyCredential, error) {
	row := q.db.QueryRow(ctx, updatePasskeyCredentialName, arg.ID, arg.UserID, arg.Name)
	var i AuthPasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceInfo,
		&i.CredentialID,
		&i.PublicKey,
		&i.AttestationType,
		&i.Transports,
		&i.Aaguid,
		&i.SignCount,
		&i.CloneWarning,
		&i.UserPresent,
		&i.UserVerified,
		&i.BackupEligible,
		&i.BackupState,
		&i.Attachment,
		&i.LastUsedAt,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
