// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateUserLoginInfo = `-- name: UpdateUserLoginInfo :exec
UPDATE public.auth_user
SET last_login_at = NOW(),
    login_count   = COALESCE(login_count, 0) + 1,
    updated       = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLoginInfo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLoginInfo, id)
	return err
}

const updateUserSecret = `-- name: UpdateUserSecret :exec
UPDATE public.auth_user
SET secret  = $2,
    updated = NOW()
WHERE id = $1
`

type UpdateUserSecretParams struct {
	ID     int64       `json:"id"`
	Secret pgtype.Text `json:"secret"`
}

func (q *Queries) UpdateUserSecret(ctx context.Context, arg UpdateUserSecretParams) error {
	_, err := q.db.Exec(ctx, updateUserSecret, arg.ID, arg.Secret)
	return err
}

const userById = `-- name: UserById :one
SELECT id, phone, email, nickname, "group", enabled, created, updated, aid, secret, last_login_at, login_count, avatar, is_verified
FROM public.auth_user
WHERE id = $1
`

func (q *Queries) UserById(ctx context.Context, id int64) (AuthUser, error) {
	row := q.db.QueryRow(ctx, userById, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Group,
		&i.Enabled,
		&i.Created,
		&i.Updated,
		&i.Aid,
		&i.Secret,
		&i.LastLoginAt,
		&i.LoginCount,
		&i.Avatar,
		&i.IsVerified,
	)
	return i, err
}

const userByPhone = `-- name: UserByPhone :one
SELECT id, phone, email, nickname, "group", enabled, created, updated, aid, secret, last_login_at, login_count, avatar, is_verified
FROM public.auth_user
WHERE phone = $1
`

func (q *Queries) UserByPhone(ctx context.Context, phone pgtype.Text) (AuthUser, error) {
	row := q.db.QueryRow(ctx, userByPhone, phone)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Group,
		&i.Enabled,
		&i.Created,
		&i.Updated,
		&i.Aid,
		&i.Secret,
		&i.LastLoginAt,
		&i.LoginCount,
		&i.Avatar,
		&i.IsVerified,
	)
	return i, err
}
