// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockUserForCredentialChange = `-- name: LockUserForCredentialChange :one
SELECT id
FROM public.auth_user
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserForCredentialChange(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserForCredentialChange, id)
	err := row.Scan(&id)
	return id, err
}

const updateUserLoginInfo = `-- name: UpdateUserLoginInfo :exec
UPDATE public.auth_user
SET last_login_at = NOW(),
    login_count   = COALESCE(login_count, 0) + 1,
    updated       = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLoginInfo(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLoginInfo, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :execrows
UPDATE public.auth_user
SET phone = $2,
    email = $3,
    nickname = $4,
    updated = NOW()
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID       int64       `json:"id"`
	Phone    pgtype.Text `json:"phone"`
	Email    pgtype.Text `json:"email"`
	Nickname pgtype.Text `json:"nickname"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.Phone,
		arg.Email,
		arg.Nickname,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const userById = `-- name: UserById :one
SELECT id, phone, email, nickname, "group", enabled, created, updated, aid, last_login_at, login_count, avatar, is_verified
FROM public.auth_user
WHERE id = $1
`

func (q *Queries) UserById(ctx context.Context, id int64) (AuthUser, error) {
	row := q.db.QueryRow(ctx, userById, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Group,
		&i.Enabled,
		&i.Created,
		&i.Updated,
		&i.Aid,
		&i.LastLoginAt,
		&i.LoginCount,
		&i.Avatar,
		&i.IsVerified,
	)
	return i, err
}

const userByPhone = `-- name: UserByPhone :one
SELECT id, phone, email, nickname, "group", enabled, created, updated, aid, last_login_at, login_count, avatar, is_verified
FROM public.auth_user
WHERE phone = $1
`

func (q *Queries) UserByPhone(ctx context.Context, phone pgtype.Text) (AuthUser, error) {
	row := q.db.QueryRow(ctx, userByPhone, phone)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Group,
		&i.Enabled,
		&i.Created,
		&i.Updated,
		&i.Aid,
		&i.LastLoginAt,
		&i.LoginCount,
		&i.Avatar,
		&i.IsVerified,
	)
	return i, err
}
